// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=repository_mock.go -package=timeselection
//

// Package timeselection is a generated GoMock package.
package timeselection

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteSelection mocks base method.
func (m *MockRepository) DeleteSelection(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSelection", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSelection indicates an expected call of DeleteSelection.
func (mr *MockRepositoryMockRecorder) DeleteSelection(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSelection", reflect.TypeOf((*MockRepository)(nil).DeleteSelection), id)
}

// UpdateSelection mocks base method.
func (m *MockRepository) UpdateSelection(to *TimeSelection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSelection", to)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSelection indicates an expected call of UpdateSelection.
func (mr *MockRepositoryMockRecorder) UpdateSelection(to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSelection", reflect.TypeOf((*MockRepository)(nil).UpdateSelection), to)
}
